# Use the spec.group/spec.versions[0].name defined in the XRD
apiVersion: crossplane.fnietoga.me/v1alpha1
# Use the spec.claimName or spec.name specified in the XRD
kind: XtStorageAccount
metadata:
  # Only claims are namespaced, unlike XRs.
  namespace: tests
  name: storage-account-minimal
spec:
  # The compositionRef specifies which Composition this XR will use to compose
  # resources when it is created, updated, or deleted.
  compositionRef:
    name: XtStorageAccount-minimalparams
  
  # Parameters for the Composition to provide the Managed Resources (MR) with
  # to create the actual infrastructure components
  parameters:
    resourceGroupName: RG-WE-D-TESTAPP-01
    location: westeurope
    environment: development
    projectName: testapp02